import "./globals.css";
import Navbar from "../components/navbar";
import { UserAuthContextProvider } from "@/components/UserAuthContext";

export const metadata = {
  title: "Next",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html data-theme="light" lang="en">
      <body className="tracking-wide">
        <UserAuthContextProvider>
          <div className="">
            <div className="flex justify-center items-center sticky top-3 mt-3 z-10 ">
              <Navbar />
            </div>
            <div> {children}</div>
          </div>
        </UserAuthContextProvider>
      </body>
    </html>
  );
}
